version: '3.7'
services:
  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:latest
    volumes:
      - ./music_browser:/config/custom_components/music_browser
    environment:
      - TZ=Europe/Zurich
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123